DROP TABLE NOTICE CASCADE CONSTRAINTS;

CREATE TABLE NOTICE(
	NOTICE_NO NUMBER,
	NOTICE_TITLE VARCHAR2(30) NOT NULL,
	NOTICE_WRITER VARCHAR2(15) NOT NULL,
	NOTICE_DATE DATE DEFAULT SYSDATE,
	NOTICE_CONTENT VARCHAR2(2000),
	FILE_PATH VARCHAR2(100),
	CONSTRAINT PK_NOTICENO PRIMARY KEY (NOTICE_NO),
	CONSTRAINT FK_NWRITER FOREIGN KEY(NOTICE_WRITER) REFERENCES MEMBER(ID)
);

CREATE SEQUENCE SEQ_NOTICE
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999
	NOCACHE
	NOCYCLE
;

INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'관리자 공지 1','admin',TO_DATE('2017-01-05','RRRR-MM-DD'),'공지서비스입니다. <br>많이 이용해주세요~!!',NULL);
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'관리자 공지 2','admin',TO_DATE('2017-04-15','RRRR-MM-DD'),'첫번째 게시글 입니다~!!',NULL);
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'유저 작성 1','user11',TO_DATE('2017-07-10','RRRR-MM-DD'),'하이염',NULL);
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'유저 작성 2','user22',TO_DATE('2017-07-11','RRRR-MM-DD'),'반갑습니다, 잘 지내봐여',NULL);
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'유저 작성 3','user11',TO_DATE('2017-07-12','RRRR-MM-DD'),'네 신사임당님 하이여',NULL);
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'유저 작성 4','user22',TO_DATE('2017-07-13','RRRR-MM-DD'),'요즘 날씨 더운데, 아이스크림 드시러 가실 분!',NULL);
INSERT INTO NOTICE VALUES(SEQ_NOTICE.NEXTVAL,'유저 작성 8','user22',TO_DATE('2017-07-17','RRRR-MM-DD'),'라면먹고 싶어요.','/first/images/1.jpg');

SELECT * FROM NOTICE;
COMMIT;