/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-07-29 04:53:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import member.model.vo.*;

public final class loginout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member member = (Member) session.getAttribute("member");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie ie8\" class=\"no-js\" lang=\"ko\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"ko\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<title>로그인 페이지 - MAːDÆ</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/icon.ico\">\r\n");
      out.write("<!-- CSS FILES -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\"\r\n");
      out.write("\tmedia=\"screen\" data-name=\"skins\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout/wide.css\" data-name=\"layout\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/fractionslider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style-fraction.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/switcher.css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--Start Header-->\r\n");
      out.write("\t<header id=\"header\" class=\"clearfix\">\r\n");
      out.write("\t\t<div id=\"top-bar\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7 hidden-xs top-info\">\r\n");
      out.write("\t\t\t\t\t\t<!--                        <span><i class=\"fa fa-phone\"></i>Phone: (123) 456-7890</span>\r\n");
      out.write("                        <span><i class=\"fa fa-envelope\"></i>Email: firerain4@naver.com</span>-->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-5 top-info\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- LOGO bar -->\r\n");
      out.write("\t\t<div id=\"logo-bar\" class=\"clearfix\">\r\n");
      out.write("\t\t\t<!-- Container -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<!-- Logo / Mobile Menu -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"logo\" style=\"width: 170px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.jsp\"><img src=\"images/logo.png\" alt=\"Eve\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Container / End -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--LOGO bar / End-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Navigation\r\n");
      out.write("================================================== -->\r\n");
      out.write("\t\t<div class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/notice/공지사항 main.html\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">DIY 상품</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"portfolio_2.html\">Designed</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"portfolio_2.html\">Parts</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/mypage/order_page.html\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"views/mypage/myinfo.html\">My page</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"views/mypage/order_page.html\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"views/mypage/myinfo.html\">회원정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"views/mypage/myinfo.html\">쪽지함</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"views/mypage/myinfo.html\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/faq/faq.html\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/.row -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.container -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--End Header-->\r\n");
      out.write("\r\n");
      out.write("\t<!--start wrapper-->\r\n");
      out.write("\t<section class=\"wrapper\">\r\n");
      out.write("\t\t<section class=\"page_head\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<h2>로그인 페이지 - MAːDÆ</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!--start info service-->\r\n");
      out.write("\t\t<section class=\"content\">\r\n");
      out.write("\t\t\t<div class=\"container\" id=\"loginForm\">\r\n");
      out.write("\t\t\t\t");

					if (member == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>아이디 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>비밀번호 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"pwd\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><p><br><input type=\"submit\" class=\"btn btn-default\" value=\"로그인\">&nbsp;&nbsp;<a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"views/user/%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%ED%8E%98%EC%9D%B4%EC%A7%80.html\">&nbsp;회원가입&nbsp;</a></p></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>환영합니다. ");
      out.print(member.getName());
      out.write("님!!!!\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"logout\">로그아웃</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--end wrapper-->\r\n");
      out.write("\r\n");
      out.write("\t<!--start footer-->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>About Us</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<p>본 프로젝트는 KH정보교육원 [NCS]웹 개발 응용SW엔지니어 양성과정_2주차 오후반 3조에서 만든\r\n");
      out.write("\t\t\t\t\t\t\tSemi 프로젝트입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact-details-alt\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Address</strong>: 서울시 강남구 역삼동\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Phone</strong>: 010-5688-2293\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Email</strong>: <a href=\"#\">firerain4@naver.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Recent Posts</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Aenean\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcommodo ligula eget dolor<span>November 07, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Temporibus\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautem quibusdam <span>November 05, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Debitis\r\n");
      out.write("\t\t\t\t\t\t\t\t\taut rerum saepe <span>November 03, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Et\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvoluptates repudiandae <span>November 02, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Twitter</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"tweet_list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tweet_content item\"><i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tweet_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">@jquery_rain </a> Lorem ipsum dolor et, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipiscing eli\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> <span class=\"time\">29 September 2014</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tweet_content item\"><i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tweet_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">@jquery_rain </a> Lorem ipsum dolor et, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipiscing eli\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> <span class=\"time\">29 September 2014</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tweet_content item\"><i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tweet_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">@jquery_rain </a> Lorem ipsum dolor et, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipiscing eli\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> <span class=\"time\">29 September 2014</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tweet_go\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Flickr Gallery</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"flickr\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"flickrFeed\" class=\"flickr-feed\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!--end footer-->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer_bottom\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t&copy; Copyright 2017 MAːDÆ | Powered by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://www.jqueryrain.com/\">jQuery Rain</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer_social\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footbot_social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"fb\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Facbook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twtr\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dribbble\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Dribbble\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"skype\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Skype\"><i class=\"fa fa-skype\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"rss\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"RSS\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<!-- jQuery cookie -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/styleswitch.js\"></script>\r\n");
      out.write("\t<!-- Style Colors Switcher -->\r\n");
      out.write("\t<script src=\"js/jquery.fractionslider.js\" type=\"text/javascript\"\r\n");
      out.write("\t\tcharset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.smartmenus.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/jquery.smartmenus.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.jcarousel.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jflickrfeed.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/swipe.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-scrolltofixed-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Style Switcher -->\r\n");
      out.write("\t<div class=\"switcher\"></div>\r\n");
      out.write("\t<!-- End Style Switcher -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
