/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-08-08 19:53:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import part.model.vo.Part;
import design.model.vo.Design;
import member.model.vo.*;
import java.sql.*;
import java.util.ArrayList;
import member.model.vo.*;

public final class designedDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/item/../../header.jsp", Long.valueOf(1502037304006L));
    _jspx_dependants.put("/views/item/../../footer.jsp", Long.valueOf(1502187510265L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("design.model.vo.Design");
    _jspx_imports_classes.add("part.model.vo.Part");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Design d = (Design) request.getAttribute("design");
	int oriPrice = (int) request.getAttribute("oriPrice");
	int likechk = ((Integer)request.getAttribute("like")).intValue();
	ArrayList<Part> plist = (ArrayList<Part>) request.getAttribute("plist");
	ArrayList<ItemReview> reviewList = (ArrayList<ItemReview>) request.getAttribute("review");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie ie8\" class=\"no-js\" lang=\"ko\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"ko\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<title>");
      out.print(d.getDesignName());
      out.write(" Detail - MAːDÆ</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/made/images/icon.ico\">\r\n");
      out.write("<!-- CSS FILES -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/made/css/style.css\"\r\n");
      out.write("\tmedia=\"screen\" data-name=\"skins\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/layout/wide.css\"\r\n");
      out.write("\tdata-name=\"layout\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/fractionslider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/style-fraction.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/made/css/switcher.css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("<style>\r\n");
      out.write("button.like {\r\n");
      out.write("\tbackground: #fcabdd;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.unlike {\r\n");
      out.write("\tbackground: #efdee9;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#like:hover {\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\tcolor: #fcabdd;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Start Header-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member) session.getAttribute("member");
	String loginout;
	String[] addr = new String[3];
	
	if (m == null) {
		loginout = "<a href='#login-modal' data-toggle='modal' data-target='#login-modal'>&nbsp;Login&nbsp;</a>";
		//loginout = "<a href='/made/loginout.jsp'>&nbsp;Login&nbsp;</a>";
	} else {
		loginout = "&nbsp;<b>" + m.getNickName()
				+ "</b>님 환영합니다!&nbsp;&nbsp;<a href='/made/logout'>&nbsp;Logout&nbsp;</a>";
		addr = m.getAddress().split(",");
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/made/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script src=\"/made/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 서브메뉴 색상 변경 jQuery -->\r\n");
      out.write("<script>\r\n");
      out.write("\t/* $(function() {\r\n");
      out.write("\t\t//console.log(\"현 경로 : \"+currentPath);\r\n");
      out.write("\t\t$(\".navbar-nav > li\").each(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t$(this).on('click',function(){\r\n");
      out.write("\t\t\t\t\t\t$(\".navbar-nav > li\").not($(this)).removeClass('active');\r\n");
      out.write("\t\t\t        \t$(this).addClass('active');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}); */\r\n");
      out.write("\t var currentPath = window.location.pathname.substr(window.location.pathname.lastIndexOf(\"/\")+1);\r\n");
      out.write("\t//console.log(currentPath);\r\n");
      out.write("\t//console.log(window.location.pathname);\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//console.log(\"현 경로 : \"+currentPath);\r\n");
      out.write("\t\t$(\".navbar-nav > li\").each(function(){\r\n");
      out.write("\t        var usePage = $(this).children('a').attr('href').substr($(this).children('a').attr('href').lastIndexOf(\"/\")+1);\r\n");
      out.write("\t        //console.log(usePage);\r\n");
      out.write("\t        if(currentPath == usePage){\r\n");
      out.write("\t        \t$(\".navbar-nav > li\").not($(this)).removeClass('active');\r\n");
      out.write("\t        \t$(this).addClass('active');\r\n");
      out.write("\t        } else if(currentPath.indexOf(\"item\") != -1 \r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"part\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"design\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"dDetail\") != -1 \r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"pDetail\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"pup\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"dup\") != -1){\r\n");
      out.write("                $(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#item\").addClass('active');\r\n");
      out.write("\t        } else if(currentPath.indexOf(\"notice\") != -1 || currentPath.indexOf(\"nlist\") != -1 || currentPath.indexOf(\"ndetail\") != -1){\r\n");
      out.write("                $(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#notice\").addClass('active');\r\n");
      out.write("            } else if (currentPath.indexOf(\"mypage\") != -1 || currentPath.indexOf(\"order\") != -1 || currentPath.indexOf(\"qlist\") != -1  || currentPath.indexOf(\"qa\") != -1 || currentPath.indexOf(\"qdetail\") != -1 || currentPath.indexOf(\"qmlist\") != -1){\r\n");
      out.write("            \t$(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#mypage\").addClass('active');\r\n");
      out.write("            } else {\r\n");
      out.write("            \t$(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("            \t$(\".navbar-nav > li\").eq(0).addClass('active');\r\n");
      out.write("            }\r\n");
      out.write("\t        //console.log(\"참조할 경로 : \"+$(this).children('a').attr('href').substr($(this).children('a').attr('href').lastIndexOf(\"/\")+1));\r\n");
      out.write("\t    });\r\n");
      out.write("\t}); \r\n");
      out.write("</script>\r\n");
      out.write("<!-- 서브메뉴 색상 변경 End -->\r\n");
      out.write("<!-- Modal Start -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".modal-dialog {\r\n");
      out.write("    width: 300px;\r\n");
      out.write("}\r\n");
      out.write(".modal-footer {\r\n");
      out.write("    height: 70px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".modal-footer .btn {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".input-group-addon {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background: #3276B1;\r\n");
      out.write("}\r\n");
      out.write(".prettyline {\r\n");
      out.write("  height: 5px;\r\n");
      out.write("  border-top: 0;\r\n");
      out.write("  background: #c4e17f;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("    $('.modal-footer > button').click(function(){\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("\t\t\turl : \"/made/login\",\r\n");
      out.write("\t\t\tdata : {id : $('#uLogin').val(), pwd : $('#uPassword').val()},\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\tif(result == \"ok\"){\r\n");
      out.write("\t\t\t\t\talert(\"로그인 성공!\");\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/made/index.jsp\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"로그인 실패!! 입력값을 재확인 하세요!\");\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/made/index.jsp\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, error : function(request,status,error) {\r\n");
      out.write("\t\t\t\talert(\"ERROR code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t\tlocation.href = \"/made/404-page.jsp?message='로그인 서비스 실패'\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("    \t$('#login-modal').modal('hide');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write(" <div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t<p class=\"modal-title\" id=\"myModalLabel\" align=\"center\">\r\n");
      out.write("\t\t\t\t<img src=\"/made/images/logo.png\" style=\"height:30px; width:auto; margin-top: -6px;\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;<b style=\"font-size: 16pt;\">Log in</b></p>\r\n");
      out.write("\t\t\t</div> <!-- /.modal-header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form role=\"form\" id=\"loginform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"uLogin\" class=\"input-group-addon glyphicon glyphicon-user\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"uLogin\" placeholder=\"Login\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> <!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"uPassword\" class=\"input-group-addon glyphicon glyphicon-lock\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"uPassword\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /.input-group -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /.form-group -->\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div> <!-- /.modal-body -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"form-control btn btn-default btn-block\">Ok</button>\r\n");
      out.write("\t\t\t</div> <!-- /.modal-footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div><!-- /.modal-content -->\r\n");
      out.write("\t</div><!-- /.modal-dialog -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("<!-- Modal End -->\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 여부를 확인하고 로그인 모달 창 호출 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#mypage ul li a').on(\"click\", function(){\r\n");
      out.write("\t\t\tif($('a').first().text().trim() == \"Login\"){\r\n");
      out.write("\t\t\t\t$(\"#login-modal\").modal();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"header\" class=\"clearfix\">\r\n");
      out.write("\t<div id=\"top-bar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-7 hidden-xs top-info\">\r\n");
      out.write("\t\t\t\t\t<!--                        <span><i class=\"fa fa-phone\"></i>Phone: (123) 456-7890</span>\r\n");
      out.write("                        <span><i class=\"fa fa-envelope\"></i>Email: firerain4@naver.com</span>-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5 top-info\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li>");
      out.print(request.getRequestURL());
      out.write("</li> -->\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: auto;\">");
      out.print(loginout);
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t");

							if (m == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/made/views/user/signup.jsp\">&nbsp;회원가입&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- LOGO bar -->\r\n");
      out.write("\t<div id=\"logo-bar\" class=\"clearfix\">\r\n");
      out.write("\t\t<!-- Container -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Logo / Mobile Menu -->\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" style=\"width: 170px;\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/made/index.jsp\"><img src=\"/made/images/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Made\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Container / End -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--LOGO bar / End-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation\r\n");
      out.write("================================================== -->\r\n");
      out.write("\t<div class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"notice\"><a href=\"/made/nilst?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"item\"><a href=\"#\">DIY 상품</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/designitemlist?page=1\">Designed</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/partitemlist?page=1\">Parts</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"mypage\"><a href=\"/made/views/mypage/order_page.html\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">My page</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/corderlist\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">회원정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">쪽지함</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(m != null && m.getClassCode().charAt(0) == 'A'){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/qlist?page=1\">1:1문의확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/views/qa/qa.jsp\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/views/faq/faq.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/views/default_page/default_page.jsp\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.row -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/.container -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\t<!--End Header-->\r\n");
      out.write("\r\n");
      out.write("\t<!--start wrapper-->\r\n");
      out.write("\t<section class=\"wrapper\">\r\n");
      out.write("\t\t<section class=\"page_head\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t");
 if (m != null && m.getClassCode().equals("A")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h2>Item ");
      out.print(d.getDesignName());
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" onclick=\"location.href='/made/dupView?id=");
      out.print(d.getDesignId());
      out.write("';\">수정하기</button>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" onclick=\"location.href='/made/ddelete?id=");
      out.print(d.getDesignId());
      out.write("';\">삭제하기</button></h2>\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h2>Item ");
      out.print(d.getDesignName());
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"content portfolio_single\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row sub_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-7 col-md-7 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<!--Project Details Page-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"porDetCarousel\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"carousel-item active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 500px; height: 400px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"/made/images/items/designed/");
      out.print(d.getDesignImg());
      out.write("\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-5 col-md-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"project_details\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Item Purchase</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>Designed by </span>");
      out.print(d.getDesignerId());
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>재질:</span>");
      out.print(d.getDesignCategory());
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>사용된 자재:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(plist.size() != 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(Part p : plist) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><td><a href=\"/made/pDetail?id=");
      out.print(p.getPartId());
      out.write("&page=1\"><b>");
      out.print(p.getPartName() );
      out.write("</b></a>&nbsp;&nbsp;");
      out.print(p.getPrice() );
      out.write("원 &nbsp;&nbsp; ");
      out.print(p.getQuantity() );
      out.write("개</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t제공 자재 없음\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>디자인 가격:</span>");
      out.print(d.getDesignPrice());
      out.write("원</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>완제품 구매:</span><input type=\"checkbox\" name=\"chk\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"chk\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>구매수량 :</span><input type=\"number\" name=\"quan\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmin=\"1\" max=\"99\" value=\"1\" id=\"quan\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>총 가격 :</span><input type=\"number\" id=\"price\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"price\" readonly></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<p align=\"center\">");
 if(m != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(likechk != 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default like\" id=\"like\">♥ 찜 취소</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default unlike\" id=\"like\">♥ 찜하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" onclick=\"orderGo();\">주문하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row sub_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dividerHeading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Item Descriptions</span>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-tabs\" id=\"myTab\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a data-toggle=\"tab\" href=\"#Popular\">상품설명 &amp; 상품 설계</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a data-toggle=\"tab\" href=\"#Recent-Comment\">Comment</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content clearfix\" id=\"myTabContent\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Popular\" class=\"tab-pane fade active in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(d.getDesignDesc());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Recent-Comment\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"comments\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(reviewList.size() != 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 for(ItemReview rv : reviewList) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"comments_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"reviewCode\" class=\"reviewCode\" name=\"reviewCode\" value=\"");
      out.print(rv.getReviewCode());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"post-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img width=\"60\" height=\"60\" alt=\"#\" src=\"/made/images/userimage/");
      out.print(rv.getMemberImg());
      out.write("\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong style=\"font-size:14pt;\"><a href=\"#\">");
      out.print(rv.getMemberId());
      out.write("</a> <i style=\"font-size:10pt;\">says: ");
      out.print(rv.getReviewDate());
      out.write("</i><br><br></strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"reviewContents\" id=\"reviewContents\" style=\"margin-top:-15px; padding-left: 71px; font-size:11pt; color:black;\">");
      out.print(rv.getReviewContent());
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 if( rv.getMemberId().equals(m.getId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-xs updateConfirm\" name=\"updateConfirm\" id=\"updateConfirm\" style=\"display: none;\">수정완료</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<button type=\"button\" class=\"btn btn-default btn-xs update\" name=\"update\" id=\"update\">수정하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<button type=\"button\" class=\"btn btn-default btn-xs delete\" name=\"delete\" id=\"delete\">삭제하기</button></p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 }}} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"comments_list clearfix\"> <h3>현재 등록된 후기가 없습니다.</h3> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"writeReview\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dividerHeading\">\r\n");
      out.write("                               \t\t\t\t <h4><span>후기 작성하기</span></h4>\r\n");
      out.write("                               \t\t\t\t </div>\r\n");
      out.write("                               <form action=\"/made/dreviewinsert\" method=\"post\">\r\n");
      out.write("                               \t<input type=\"hidden\" id=\"mid\" name=\"mid\" value=\"");
      out.print(m.getId());
      out.write("\">\r\n");
      out.write("                               \t<input type=\"hidden\" id=\"did\" name=\"did\" value=\"");
      out.print(d.getDesignId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea id=\"content\" name=\"content\" class=\"summernote\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\" id=\"reviewSubmit\">등록하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"reviewReset\">취소하기</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#chk\").removeAttr('checked');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#quan\").val(1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                    $(\".updateConfirm\").on('click',function(){\r\n");
      out.write("                                        var parentP = $(this).parent();\r\n");
      out.write("                                        var parentLi = parentP.parent();\r\n");
      out.write("                                        var siblingP = parentLi.children('p:eq(0)');\r\n");
      out.write("                                        var reviewCode = parentLi.children('input').val();\r\n");
      out.write("                                        var updtContent = parentP.children(\".updateContent\").val();\r\n");
      out.write("                                        //console.log(updtContent);\r\n");
      out.write("                                        $.ajax({\r\n");
      out.write("                                            url : \"/made/dupReview\",\r\n");
      out.write("                                            type : \"post\",\r\n");
      out.write("                                            data: {\r\n");
      out.write("                                            \tdesignCode : \"");
      out.print(d.getDesignId());
      out.write("\",\r\n");
      out.write("                                            \tmid : \"");
      out.print(m.getId());
      out.write("\",\r\n");
      out.write("                                                reviewCode : reviewCode,\r\n");
      out.write("                                                updtContent : updtContent\r\n");
      out.write("                                            },\r\n");
      out.write("                                            success : function(data) {\r\n");
      out.write("                                            \talert(data);\r\n");
      out.write("                                            }, error : function(request,status,error) {\r\n");
      out.write("                                               alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("                                            }\r\n");
      out.write("                                        });\r\n");
      out.write("                                        \r\n");
      out.write("                                        parentLi.find(\".reviewContents\").html(updtContent);\r\n");
      out.write("                                        parentP.children(\".updateContent\").remove();\r\n");
      out.write("                                        parentP.children(\".updateConfirm\").toggle(\"fast\");\r\n");
      out.write("                                        parentP.children('.update').text(\"수정하기\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".update\").on('click',function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar parentP = $(this).parent();\r\n");
      out.write("                                        var parentLi = parentP.parent();\r\n");
      out.write("                                        var siblingP = parentLi.children('p:eq(0)');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar content = parentLi.children('.reviewContents').text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif($(this).text() == \"수정하기\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tparentP.append('<textarea style=\"margin-top:7px;\" class=\"updateContent\" name=\"updateContent\" id=\"updateContent\">'+content+'</textarea>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tparentP.children(\".updateConfirm\").toggle(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(this).text(\"수정취소\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//alert(\"수정 합니다~\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tparentP.children(\".updateContent\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(this).text(\"수정하기\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tparentP.children(\".updateConfirm\").toggle(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//alert(\"수정 취소합니다~\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".delete\").on('click',function(){\r\n");
      out.write("                                        var parentP = $(this).parent();\r\n");
      out.write("                                        var parentLi = parentP.parent();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar reviewCode = parentLi.children('input').val();\r\n");
      out.write("                                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("                                            url : \"/made/dDelReview\",\r\n");
      out.write("                                            type : \"post\",\r\n");
      out.write("                                            data: {\r\n");
      out.write("                                            \tdesignCode : \"");
      out.print(d.getDesignId());
      out.write("\",\r\n");
      out.write("                                            \tmid : \"");
      out.print(m.getId());
      out.write("\",\r\n");
      out.write("                                            \treviewCode : reviewCode\r\n");
      out.write("                                            },\r\n");
      out.write("                                            success : function(data) {\r\n");
      out.write("                                                alert(data);\r\n");
      out.write("                                                parentLi.remove();\r\n");
      out.write("                                            }, error : function(request,status,error) {\r\n");
      out.write("                                               alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("                                            }\r\n");
      out.write("                                    });\r\n");
      out.write("                                });\r\n");
      out.write("                                    summernote();\r\n");
      out.write("                                    $('#reviewReset').on('click',function(){\r\n");
      out.write("                                \t\t$('.summernote').summernote('reset');\r\n");
      out.write("                                \t\tsummernote();\r\n");
      out.write("                                \t});\r\n");
      out.write("                                    $('#reviewSubmit').on('submit',function(event){\r\n");
      out.write("                                    \tif ($('#summernote').summernote('isEmpty')) {\r\n");
      out.write("                                      \t  alert('후기 란이 비어 있습니다.');\r\n");
      out.write("                                      \t  event.preventDefault();\r\n");
      out.write("                                      } else {\r\n");
      out.write("                                    \t  return;\r\n");
      out.write("                                      }\r\n");
      out.write("                                \t});\r\n");
      out.write("                                });\r\n");
      out.write("                                    \r\n");
      out.write("                                    function summernote(){\r\n");
      out.write("                                        $('.summernote').summernote({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      width: '100%',\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t      height: 100,          // 기본 높이값\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      minHeight: null,      // 최소 높이값(null은 제한 없음)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      maxHeight: null,      // 최대 높이값(null은 제한 없음)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      focus: true,          // 페이지가 열릴때 포커스를 지정함\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      lang: \"ko-KR\",         // 한국어 지정(기본값은 en-US)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      placeholder: '여기에 후기를 작성해주세요~!!',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      callbacks: {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      onImageUpload: function(files, editor, welEditorble) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t  console.log(files);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t  console.log(files[0]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata = new FormData();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata.append(\"file\",files[0]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar $note = $(this);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\turl : '/made/designUploadImg', // servlet url\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(url){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//alert(url);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$note.summernote('insertImage',url);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}, error : function(request,status,error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("                                                }\r\n");
      out.write("                                            });\r\n");
      out.write("                                          }\r\n");
      out.write("                                          }\r\n");
      out.write("                                        });\r\n");
      out.write("\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row sub_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-intro\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dividerHeading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Recently Designed Item</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-navi\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"work-prev\" class=\"arrow-left jcarousel-prev\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-angle-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"work-next\" class=\"arrow-right jcarousel-next\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"jcarousel recent-work-jc\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"jcarousel-list\">\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--End wrapper-->\r\n");
      out.write("\t\t<!--start footer-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\"> -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>About Us</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<p>본 프로젝트는 KH정보교육원 [NCS]웹 개발 응용SW엔지니어 양성과정_2주차 오후반 3조에서 만든\r\n");
      out.write("\t\t\t\t\t\t\tSemi 프로젝트입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact-details-alt\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Address</strong>: 서울시 강남구 역삼동\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Phone</strong>: 010-5688-2293\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Email</strong>: <a href=\"#\">firerain4@naver.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Flickr Gallery</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"flickr\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"flickrFeed\" class=\"flickr-feed\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer_bottom\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t&copy; Copyright 2017 MAːDÆ | Powered by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://www.jqueryrain.com/\">jQuery Rain</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer_social\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footbot_social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"fb\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Facbook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twtr\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dribbble\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Dribbble\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"skype\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Skype\"><i class=\"fa fa-skype\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"rss\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"RSS\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<script src=\"/made/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/made/js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<!-- jQuery cookie -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/styleswitch.js?var=1\"></script>\r\n");
      out.write("\t<!-- Style Colors Switcher -->\r\n");
      out.write("\t<!-- ?ver=1 값은 브라우저 확인 시 기존 캐시값이 아닌 변경된 파일을 읽어 오라는 뜻  -->\r\n");
      out.write("\t<script src=\"/made/js/jquery.fractionslider.js\" type=\"text/javascript\"\r\n");
      out.write("\t\tcharset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.smartmenus.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/made/js/jquery.smartmenus.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.jcarousel.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jflickrfeed.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.isotope.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/swipe.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery-scrolltofixed-min.js\"></script>\r\n");
      out.write("\t<!-- include summernote css/js-->\r\n");
      out.write("\t<link href=\"/made/api/summernote/dist/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"/made/api/summernote/dist/summernote.js\"></script>\r\n");
      out.write("\t<!-- summer note korean language pack -->\r\n");
      out.write("\t<script src=\"/made/api/summernote/dist/lang/summernote-ko-KR.js\"></script>\r\n");
      out.write("\t<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"/made/js/main.js\"></script>\r\n");
      out.write("\t<!-- Start Style Switcher -->\r\n");
      out.write("\t<div class=\"switcher\"></div>\r\n");
      out.write("\t<!-- End Style Switcher -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Slider Setting -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t$('.slider').fractionSlider({\r\n");
      out.write("\t\t\t\t'fullWidth' : true,\r\n");
      out.write("\t\t\t\t'controls' : true,\r\n");
      out.write("\t\t\t\t'responsive' : true,\r\n");
      out.write("\t\t\t\t'dimensions' : \"1920,450\",\r\n");
      out.write("\t\t\t\t'increase' : true,\r\n");
      out.write("\t\t\t\t'pauseOnHover' : true,\r\n");
      out.write("\t\t\t\t'slideEndAnimation' : true,\r\n");
      out.write("\t\t\t\t'autoChange' : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Slider Setting -->");
      out.write("\r\n");
      out.write("\t<!--end footer-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction drecent10(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/made/drecentlist',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t//console.log(data);\r\n");
      out.write("\t\t\t\tvar jsonStr = JSON.stringify(data); //객체를 문자열로 변환\r\n");
      out.write("\t\t\t\t//console.log(jsonStr);\r\n");
      out.write("\t\t\t\tvar json = JSON.parse(jsonStr); //문자열을 배열 객체로 바꿈\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar values = $(\".jcarousel-list\").html();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfor ( var i in json.list) {\r\n");
      out.write("\t\t\t\t\t//한글 깨짐을 막기 위해 문자 인코딩 처리한 json 객체의 값은 decodeURIComponent() 로 디코딩 처리함\r\n");
      out.write("\t\t\t\t\tvalues += '<li class=\"col-sm-3 col-md-3 col-lg-3\">'\r\n");
      out.write("\t\t\t\t\t+'<div class=\"recent-item\"> <figure> <div class=\"touching medium\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t+' <img src=\"/made/images/items/designed/'+json.list[i].image+'\" style=\"width:200px;height:170px;\" alt=\"\" />'\r\n");
      out.write("\t\t\t\t\t\t\t+' </div> <div class=\"option\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t+' <a href=\"javascript:CaricaFoto(\\'/made/images/items/designed/'+json.list[i].image+'\\')\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t+'\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>'\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if( m!= null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t+' <a href=\"dDetail?id='+json.list[i].designCode+'\" class=\"hover-link\"><i class=\"fa fa-link\"></i></a>'\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t+' </div> <figcaption class=\"item-description\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t+' <h5>'+json.list[i].category+'</h5>'\r\n");
      out.write("\t\t\t\t\t\t\t\t+' <span>'+decodeURIComponent(json.list[i].title)+'</span>'\r\n");
      out.write("\t\t\t\t\t\t\t\t+' </figcaption> </figure> </div> </li>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\".jcarousel-list\").html(values);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(request,status,error) {\r\n");
      out.write("\t\t\t\talert(\"code:\"+request.status+\"\\nmessage:\"+request.responseText+\"\\nerror:\"+error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction CaricaFoto(img){ \r\n");
      out.write("\t\tfoto1= new Image(); \r\n");
      out.write("\t\tfoto1.src=(img); \r\n");
      out.write("\t\tControlla(img); \r\n");
      out.write("\t}; \r\n");
      out.write("\tfunction Controlla(img){ \r\n");
      out.write("\t\tif((foto1.width!=0)&&(foto1.height!=0)){ \r\n");
      out.write("\t\t\tviewFoto(img); \r\n");
      out.write("\t\t} else{ \r\n");
      out.write("\t\t\tfunzione=\"Controlla('\"+img+\"')\"; \r\n");
      out.write("\t\t\tintervallo=setTimeout(funzione,20); \r\n");
      out.write("\t\t} \r\n");
      out.write("\t}; \r\n");
      out.write("\r\n");
      out.write("\tfunction viewFoto(img){ \r\n");
      out.write("\t\t\tlargh=foto1.width+20; \r\n");
      out.write("\t\t\taltez=foto1.height+20; \r\n");
      out.write("\t\t\tstringa=\"width=\"+largh+\",height=\"+altez; \r\n");
      out.write("\t\t\tfinestra=window.open(img,\"\",stringa); \r\n");
      out.write("\t};\r\n");
      out.write("\t\tvar likechk = ");
      out.print( likechk );
      out.write(";\r\n");
      out.write("\t\tvar price = ");
      out.print(oriPrice);
      out.write(";\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tdrecent10();\r\n");
      out.write("\t\t\t$(\"#price\").val(price);\r\n");
      out.write("\t\t\t$(\"#chk\").change(function(){\r\n");
      out.write("\t\t        if($(this).is(\":checked\")){\r\n");
      out.write("\t\t        \t$(\"#price\").val($(\"#quan\").val()*");
      out.print(d.getDesignPrice());
      out.write(");\r\n");
      out.write("\t\t        }else{\r\n");
      out.write("\t\t        \t$(\"#price\").val($(\"#quan\").val()*price);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t$(\"#quan\").on(\"change\",function(){\r\n");
      out.write("\t\t\t\tif($(\"#chk\").is(\":checked\")){\r\n");
      out.write("\t\t\t\t\t$(\"#price\").val($(\"#quan\").val()*");
      out.print(d.getDesignPrice());
      out.write(");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#price\").val($(\"#quan\").val()*price);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#like\").on('click',function(){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/made/designLike\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tlike : likechk,\r\n");
      out.write("\t\t\t\t\t\tmid : \"");
      out.print(m.getId());
      out.write("\",\r\n");
      out.write("\t\t\t\t\t\tdid : \"");
      out.print(d.getDesignId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(data != 0){\r\n");
      out.write("\t\t\t\t\t\t\tlikechk = data;\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#like\").removeClass('unlike');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#like\").addClass('like');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#like\").text(\"♥ 찜 취소\");\r\n");
      out.write("\t\t\t\t\t\t\talert(\"찜하기 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tlikechk = data;\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#like\").removeClass('like');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#like\").addClass('unlike');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#like\").text(\"♥ 찜 하기\");\r\n");
      out.write("\t\t\t\t\t\t\talert(\"찜하기가 해제 되었습니다.\");\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(request,status,error) {\r\n");
      out.write("\t\t\t\t\t\talert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction orderGo(){\r\n");
      out.write("\t\t\tvar code = '");
      out.print(d.getDesignId());
      out.write("';\r\n");
      out.write("\t\t\tvar quan = Number($(\"#quan\").val());\r\n");
      out.write("\t\t\tvar price = Number($(\"#price\").val());\r\n");
      out.write("\t\t\tvar dfull = null;\r\n");
      out.write("\t\t\tif($(\"#chk\").is(\":checked\")){\r\n");
      out.write("\t\t\t\tdfull = \"Y\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdfull = \"N\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(price == 0){\r\n");
      out.write("\t\t\t\talert(\"주문하실 상품은 완제품만 구매가 가능합니다.\\n상품을 다시 선택해주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tlocation.href=\"/made/orderInfo?code=\"+code+\"&quan=\"+quan\r\n");
      out.write("\t\t\t\t+\"&price=\"+price+\"&userid=");
      out.print(m.getId());
      out.write("&dfull=\"+dfull+\"&item=design\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
