/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-07-31 10:13:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.item;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import part.model.vo.Part;
import member.model.vo.*;
import java.sql.*;
import member.model.vo.*;

public final class partDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/item/../../header.jsp", Long.valueOf(1501409210771L));
    _jspx_dependants.put("/views/item/../../footer.jsp", Long.valueOf(1501044205913L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("part.model.vo.Part");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
	
	Part p = (Part) request.getAttribute("part");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie ie8\" class=\"no-js\" lang=\"ko\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"ko\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<title>");
      out.print(p.getPartName());
      out.write(" Detail - MAːDÆ</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/made/images/icon.ico\">\r\n");
      out.write("<!-- CSS FILES -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/made/css/style.css\"\r\n");
      out.write("\tmedia=\"screen\" data-name=\"skins\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/layout/wide.css\"\r\n");
      out.write("\tdata-name=\"layout\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/fractionslider.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/made/css/style-fraction.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/made/css/switcher.css\"\r\n");
      out.write("\tmedia=\"screen\" />\r\n");
      out.write("<style>\r\n");
      out.write("button#like {\r\n");
      out.write("\tbackground: #fcabdd;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#like:hover {\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\tcolor: #fcabdd;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Start Header-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member) session.getAttribute("member");
	String loginout;
	String[] addr = new String[3];
	
	if (m == null) {
		//loginout = "<a href='#myModal' data-toggle='modal'>&nbsp;Login&nbsp;</a>";
		loginout = "<a href='/made/loginout.jsp'>&nbsp;Login&nbsp;</a>";
	} else {
		loginout = "&nbsp;<b>" + m.getNickName()
				+ "</b>님 환영합니다!&nbsp;&nbsp;<a href='/made/logout'>&nbsp;Logout&nbsp;</a>";
		addr = m.getAddress().split(",");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/made/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script src=\"/made/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 서브메뉴 색상 변경 jQuery -->\r\n");
      out.write("<script>\r\n");
      out.write("\t/* $(function() {\r\n");
      out.write("\t\t//console.log(\"현 경로 : \"+currentPath);\r\n");
      out.write("\t\t$(\".navbar-nav > li\").each(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t$(this).on('click',function(){\r\n");
      out.write("\t\t\t\t\t\t$(\".navbar-nav > li\").not($(this)).removeClass('active');\r\n");
      out.write("\t\t\t        \t$(this).addClass('active');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}); */\r\n");
      out.write("\t var currentPath = window.location.pathname.substr(window.location.pathname.lastIndexOf(\"/\")+1);\r\n");
      out.write("\t//console.log(currentPath);\r\n");
      out.write("\t//console.log(window.location.pathname);\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//console.log(\"현 경로 : \"+currentPath);\r\n");
      out.write("\t\t$(\".navbar-nav > li\").each(function(){\r\n");
      out.write("\t        var usePage = $(this).children('a').attr('href').substr($(this).children('a').attr('href').lastIndexOf(\"/\")+1);\r\n");
      out.write("\t        //console.log(usePage);\r\n");
      out.write("\t        if(currentPath == usePage){\r\n");
      out.write("\t        \t$(\".navbar-nav > li\").not($(this)).removeClass('active');\r\n");
      out.write("\t        \t$(this).addClass('active');\r\n");
      out.write("\t           } else if(currentPath.indexOf(\"item\") != -1){\r\n");
      out.write("                $(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#item\").addClass('active');\r\n");
      out.write("            } else if (currentPath.indexOf(\"mypage\") != -1){\r\n");
      out.write("            \t$(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#mypage\").addClass('active');\r\n");
      out.write("            }\r\n");
      out.write("\t        //console.log(\"참조할 경로 : \"+$(this).children('a').attr('href').substr($(this).children('a').attr('href').lastIndexOf(\"/\")+1));\r\n");
      out.write("\t    });\r\n");
      out.write("\t}); \r\n");
      out.write("</script>\r\n");
      out.write("<!-- 서브메뉴 색상 변경 End -->\r\n");
      out.write("<!-- \r\n");
      out.write("  Modal\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      Modal content\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("          <h4 class=\"modal-title\" style=\"background: gray;\"><img src=\"/made/images/logo.png\">&nbsp;Login</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <p>Some text in the modal.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(\"#myBtn\").click(function(){\r\n");
      out.write("        $(\"#myModal\").modal();\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("  Modal End\r\n");
      out.write("   -->\r\n");
      out.write("<header id=\"header\" class=\"clearfix\">\r\n");
      out.write("\t<div id=\"top-bar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-7 hidden-xs top-info\">\r\n");
      out.write("\t\t\t\t\t<!--                        <span><i class=\"fa fa-phone\"></i>Phone: (123) 456-7890</span>\r\n");
      out.write("                        <span><i class=\"fa fa-envelope\"></i>Email: firerain4@naver.com</span>-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5 top-info\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li>");
      out.print(request.getRequestURL());
      out.write("</li> -->\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: auto;\">");
      out.print(loginout);
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t");

							if (m == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/made/views/user/%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%ED%8E%98%EC%9D%B4%EC%A7%80.html\">&nbsp;회원가입&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- LOGO bar -->\r\n");
      out.write("\t<div id=\"logo-bar\" class=\"clearfix\">\r\n");
      out.write("\t\t<!-- Container -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Logo / Mobile Menu -->\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" style=\"width: 170px;\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/made/index.jsp\"><img src=\"/made/images/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Made\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Container / End -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--LOGO bar / End-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation\r\n");
      out.write("================================================== -->\r\n");
      out.write("\t<div class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/views/notice/공지사항 main.jsp\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"item\"><a href=\"#\">DIY 상품</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/designitemlist?page=1\">Designed</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/partitemlist?page=1\">Parts</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"mypage\"><a href=\"/made/views/mypage/order_page.html\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">My page</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/order_page.html\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">회원정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">쪽지함</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.html\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/views/faq/faq.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/views/default_page/default_page.jsp\">Default</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.row -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/.container -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\t<!--End Header-->\r\n");
      out.write("\r\n");
      out.write("\t<!--start wrapper-->\r\n");
      out.write("\t<section class=\"wrapper\">\r\n");
      out.write("\t\t<section class=\"page_head\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Item ");
      out.print(p.getPartName());
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"content portfolio_single\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row sub_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-7 col-md-7 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<!--Project Details Page-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"porDetCarousel\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"carousel-item active\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 500px; height: 400px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"/made/images/items/parts/");
      out.print(p.getPartCategory().toLowerCase()+"/"+p.getPartImg());
      out.write("\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-5 col-md-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"project_details\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Item Purchase</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>재질:</span>");
      out.print(p.getPartCategory());
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>가격:</span>");
      out.print(p.getPrice());
      out.write("원</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>구매수량 :</span><input type=\"number\" name=\"quan\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmin=\"1\" max=\"99\" value=\"1\" id=\"quan\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><span>총 가격 :</span><input type=\"number\" id=\"price\" \r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"price\" size=\"8\" lang=\"en\" readonly>원</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<p align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(m != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" id=\"like\">♥</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" onclick=\"pay_test();\">구매하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row sub_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dividerHeading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Item Descriptions</span>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-tabs\" id=\"myTab\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a data-toggle=\"tab\" href=\"#Popular\">상품설명</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a data-toggle=\"tab\" href=\"#Recent\">상품설계도</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a data-toggle=\"tab\" href=\"#Recent-Comment\">Comment</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content clearfix\" id=\"myTabContent\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Popular\" class=\"tab-pane fade active in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t상품 설명\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(p.getPartDesc());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Recent\" class=\"tab-pane fade\">상품 설계도.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Recent-Comment\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"comments\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"comments_list clearfix\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"post-thumbnail\"><img width=\"60\" height=\"60\" alt=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/content/recent_3.png\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong><a href=\"#\">LaraDut</a> <i>says: </i> </strong> Morbi\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taugue velit, tempus mattis dignissim nec, porta sed risus.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tDonec eget magna eu lorem tristique pellentesque eget eu dui.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFusce lacinia tempor malesuada.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"comments_list clearfix\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"post-thumbnail\"><img width=\"60\" height=\"60\" alt=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/content/recent_1.png\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong><a href=\"#\">Ronny</a> <i>says: </i> </strong> Tempus\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmattis dignissim nec, porta sed risus. Donec eget magna eu\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tlorem tristique pellentesque eget eu dui. Fusce lacinia\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttempor malesuada.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"comments_list clearfix\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"post-thumbnail\"><img width=\"60\" height=\"60\" alt=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/content/recent_2.png\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong><a href=\"#\">Steve</a> <i>says: </i> </strong> Donec\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconvallis, metus nec tempus aliquet, nunc metus adipiscing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tleo, a lobortis nisi dui ut odio. Nullam ultrices, eros\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taccumsan vulputate faucibus, turpis tortor.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row sub_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-intro\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dividerHeading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Recent Work</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-navi\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"work-prev\" class=\"arrow-left jcarousel-prev\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-angle-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"work-next\" class=\"arrow-right jcarousel-next\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"jcarousel recent-work-jc\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"jcarousel-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_1.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_2.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_3.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_4.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_5.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_1.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_2.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Recent Work Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-sm-3 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"recent-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"touching medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/portfolio/portfolio_3.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"images/portfolio/full/portfolio_1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"hover-zoom mfp-image\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"portfolio_single.html\" class=\"hover-link\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-link\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<figcaption class=\"item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Touch and Swipe</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Technology</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--End wrapper-->\r\n");
      out.write("\t<!--start footer-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\"> -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>About Us</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<p>본 프로젝트는 KH정보교육원 [NCS]웹 개발 응용SW엔지니어 양성과정_2주차 오후반 3조에서 만든\r\n");
      out.write("\t\t\t\t\t\t\tSemi 프로젝트입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact-details-alt\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Address</strong>: 서울시 강남구 역삼동\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Phone</strong>: 010-5688-2293\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Email</strong>: <a href=\"#\">firerain4@naver.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Recent Posts</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Aenean\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcommodo ligula eget dolor<span>November 07, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Temporibus\r\n");
      out.write("\t\t\t\t\t\t\t\t\tautem quibusdam <span>November 05, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Debitis\r\n");
      out.write("\t\t\t\t\t\t\t\t\taut rerum saepe <span>November 03, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-caret-right\"></i> <a href=\"#\">Et\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvoluptates repudiandae <span>November 02, 2014</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Twitter</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"tweet_list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tweet_content item\"><i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tweet_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">@jquery_rain </a> Lorem ipsum dolor et, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipiscing eli\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> <span class=\"time\">29 September 2014</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tweet_content item\"><i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tweet_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">@jquery_rain </a> Lorem ipsum dolor et, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipiscing eli\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> <span class=\"time\">29 September 2014</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tweet_content item\"><i class=\"fa fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tweet_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">@jquery_rain </a> Lorem ipsum dolor et, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipiscing eli\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> <span class=\"time\">29 September 2014</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tweet_go\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Flickr Gallery</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"flickr\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"flickrFeed\" class=\"flickr-feed\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer_bottom\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t&copy; Copyright 2017 MAːDÆ | Powered by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://www.jqueryrain.com/\">jQuery Rain</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer_social\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footbot_social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"fb\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Facbook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twtr\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dribbble\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Dribbble\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"skype\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Skype\"><i class=\"fa fa-skype\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"rss\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"RSS\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<script src=\"/made/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/made/js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<!-- jQuery cookie -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/styleswitch.js?var=1\"></script>\r\n");
      out.write("\t<!-- Style Colors Switcher -->\r\n");
      out.write("\t<!-- ?ver=1 값은 브라우저 확인 시 기존 캐시값이 아닌 변경된 파일을 읽어 오라는 뜻  -->\r\n");
      out.write("\t<script src=\"/made/js/jquery.fractionslider.js\" type=\"text/javascript\"\r\n");
      out.write("\t\tcharset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.smartmenus.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/made/js/jquery.smartmenus.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.jcarousel.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jflickrfeed.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.isotope.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/swipe.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery-scrolltofixed-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/made/js/main.js\"></script>\r\n");
      out.write("\t<!-- Start Style Switcher -->\r\n");
      out.write("\t<div class=\"switcher\"></div>\r\n");
      out.write("\t<!-- End Style Switcher -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Slider Setting -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t$('.slider').fractionSlider({\r\n");
      out.write("\t\t\t\t'fullWidth' : true,\r\n");
      out.write("\t\t\t\t'controls' : true,\r\n");
      out.write("\t\t\t\t'responsive' : true,\r\n");
      out.write("\t\t\t\t'dimensions' : \"1920,450\",\r\n");
      out.write("\t\t\t\t'increase' : true,\r\n");
      out.write("\t\t\t\t'pauseOnHover' : true,\r\n");
      out.write("\t\t\t\t'slideEndAnimation' : true,\r\n");
      out.write("\t\t\t\t'autoChange' : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Slider Setting -->");
      out.write("\r\n");
      out.write("\t<!--end footer-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar price = ");
      out.print(p.getPrice());
      out.write(";\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t//Number(\"12345\").toLocaleString('en');\r\n");
      out.write("\t\t\t$(\"#price\").val(price);\r\n");
      out.write("\t\t\t$(\"#quan\").on(\"change\",function(){\r\n");
      out.write("\t\t\t\t$(\"#price\").val($(\"#quan\").val()*price);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- I'm Port 전자결제 -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://service.iamport.kr/js/iamport.payment-1.1.2.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar IMP = window.IMP; // 생략가능\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tIMP.init('imp99940489');\r\n");
      out.write("\t\t}); // 'iamport' 대신 부여받은 \"가맹점 식별코드\"를 사용\r\n");
      out.write("\t\t// 문서 로딩될 때 바로 호출\r\n");
      out.write("\t\tfunction pay_test() {\r\n");
      out.write("\t\t\tIMP.request_pay({\r\n");
      out.write("\t\t\t\tpg : 'inicis',\r\n");
      out.write("\t\t\t\tpay_method : 'card',\r\n");
      out.write("\t\t\t\tmerchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("\t\t\t\tname : '주문명:");
      out.print(p.getPartName() );
      out.write("',\r\n");
      out.write("\t\t\t\tamount : Number($('#price').val()),\r\n");
      out.write("\t\t\t\tbuyer_email : '");
      out.print(m.getEmail());
      out.write("',\r\n");
      out.write("\t\t\t\tbuyer_name : '");
      out.print(m.getName());
      out.write("',\r\n");
      out.write("\t\t\t\tbuyer_tel : '");
      out.print(m.getPhone());
      out.write("',\r\n");
      out.write("\t\t\t\tbuyer_addr : '");
      out.print(addr[1]+" "+addr[2]);
      out.write("',\r\n");
      out.write("\t\t\t\tbuyer_postcode : '");
      out.print(addr[0]);
      out.write("',\r\n");
      out.write("\t\t\t\tm_redirect_url : '../mypage/pay_cancel.html'\r\n");
      out.write("\t\t\t}, function(rsp) {\r\n");
      out.write("\t\t\t\tif (rsp.success) {\r\n");
      out.write("\t\t\t\t\t//[1] 서버단에서 결제정보 조회를 위해 jQuery ajax로 imp_uid 전달하기\r\n");
      out.write("\t\t\t\t\tjQuery.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"/payments/complete\", //cross-domain error가 발생하지 않도록 동일한 도메인으로 전송\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\timp_uid : rsp.imp_uid\r\n");
      out.write("\t\t\t\t\t\t//기타 필요한 데이터가 있으면 추가 전달\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}).done(function(data) {\r\n");
      out.write("\t\t\t\t\t\t//[2] 서버에서 REST API로 결제정보확인 및 서비스루틴이 정상적인 경우\r\n");
      out.write("\t\t\t\t\t\tif (everythings_fine) {\r\n");
      out.write("\t\t\t\t\t\t\tvar msg = '결제가 완료되었습니다.';\r\n");
      out.write("\t\t\t\t\t\t\tmsg += '\\n고유ID : ' + rsp.imp_uid;\r\n");
      out.write("\t\t\t\t\t\t\tmsg += '\\n상점 거래ID : ' + rsp.merchant_uid;\r\n");
      out.write("\t\t\t\t\t\t\tmsg += '\\결제 금액 : ' + rsp.paid_amount;\r\n");
      out.write("\t\t\t\t\t\t\tmsg += '카드 승인번호 : ' + rsp.apply_num;\r\n");
      out.write("\t\t\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t//[3] 아직 제대로 결제가 되지 않았습니다.\r\n");
      out.write("\t\t\t\t\t\t\t//[4] 결제된 금액이 요청한 금액과 달라 결제를 자동취소처리하였습니다.\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar msg = '결제에 실패하였습니다.';\r\n");
      out.write("\t\t\t\t\tmsg += '에러내용 : ' + rsp.error_msg;\r\n");
      out.write("\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--------------------->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
