/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-08-11 11:38:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import consumer.model.vo.ConsumerOrder;
import java.sql.Date;
import java.util.ArrayList;
import member.model.vo.*;

public final class consumerOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/mypage/../../header.jsp", Long.valueOf(1502449876165L));
    _jspx_dependants.put("/views/mypage/../../footer.jsp", Long.valueOf(1502450508520L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("consumer.model.vo.ConsumerOrder");
    _jspx_imports_classes.add("java.sql.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

	ArrayList<ConsumerOrder> list = (ArrayList<ConsumerOrder>) request.getAttribute("list");
	int currentPage = ((Integer) request.getAttribute("currentPage")).intValue();
	int maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
	int startPage = ((Integer) request.getAttribute("startPage")).intValue();
	int endPage = ((Integer) request.getAttribute("endPage")).intValue();
	int listCount = ((Integer) request.getAttribute("listCount")).intValue();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie ie8\" class=\"no-js\" lang=\"ko\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!--><html class=\"no-js\" lang=\"ko\"> <!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t<title>Consumer Order - MAːDÆ</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/made/images/icon.ico\">\r\n");
      out.write("\t<!-- CSS FILES -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/made/css/bootstrap.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/made/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/made/css/style.css\" media=\"screen\" data-name=\"skins\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/made/css/layout/wide.css\" data-name=\"layout\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/made/css/fractionslider.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/made/css/style-fraction.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/made/css/switcher.css\" media=\"screen\" />\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write("\ttable * {\r\n");
      out.write("\t\ttext-align : center;\r\n");
      out.write("\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\tbutton {\r\n");
      out.write("\t\tborder : none;\r\n");
      out.write("\t\tpadding-top : 2px;\r\n");
      out.write("\t\tpadding-bottom : 2px;\r\n");
      out.write("\t\tmargin : 2px;\r\n");
      out.write("\t\tbackground : gray;\r\n");
      out.write("\t\t/* #e74c3c */\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t}\r\n");
      out.write("\tbutton:hover {\r\n");
      out.write("\t\tbackground : #e74c3c;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable span {\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\t.c_product {\r\n");
      out.write("\t\theight : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.c_product_description {\r\n");
      out.write("\t\tclear : both; \r\n");
      out.write("\t\tdisplay: table-cell;\r\n");
      out.write("\t\t\t\tvertical-align: middle;\r\n");
      out.write("\t}\r\n");
      out.write("\timg {\r\n");
      out.write("\t\tfloat : left;\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.c_review_image_div {\r\n");
      out.write("        \t\tfloat: left;\r\n");
      out.write("   \t}\r\n");
      out.write("\t.c_review_image_div li {\r\n");
      out.write("\t\tlist-style-type: none;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 68px;\r\n");
      out.write("\t    height: 68px;\r\n");
      out.write("\t    margin-right: 10px;\r\n");
      out.write("\t    border: 1px solid #dbdbdb;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Start Header-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member) session.getAttribute("member");
	String loginout;
	String[] addr = new String[3];
	
	if (m == null) {
		loginout = "<a href='#login-modal' data-toggle='modal' data-target='#login-modal'>&nbsp;Login&nbsp;</a>";
		//loginout = "<a href='/made/loginout.jsp'>&nbsp;Login&nbsp;</a>";
	} else {
		loginout = "&nbsp;<b>" + m.getNickName()
				+ "</b>님 환영합니다!&nbsp;&nbsp;<a href='/made/logout'>&nbsp;Logout&nbsp;</a>";
		addr = m.getAddress().split(",");
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/made/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script src=\"/made/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 서브메뉴 색상 변경 jQuery -->\r\n");
      out.write("<script>\r\n");
      out.write("\t/* $(function() {\r\n");
      out.write("\t\t//console.log(\"현 경로 : \"+currentPath);\r\n");
      out.write("\t\t$(\".navbar-nav > li\").each(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t$(this).on('click',function(){\r\n");
      out.write("\t\t\t\t\t\t$(\".navbar-nav > li\").not($(this)).removeClass('active');\r\n");
      out.write("\t\t\t        \t$(this).addClass('active');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}); */\r\n");
      out.write("\t var currentPath = window.location.pathname.substr(window.location.pathname.lastIndexOf(\"/\")+1);\r\n");
      out.write("\t//console.log(currentPath);\r\n");
      out.write("\t//console.log(window.location.pathname);\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//console.log(\"현 경로 : \"+currentPath);\r\n");
      out.write("\t\t$(\".navbar-nav > li\").each(function(){\r\n");
      out.write("\t        var usePage = $(this).children('a').attr('href').substr($(this).children('a').attr('href').lastIndexOf(\"/\")+1);\r\n");
      out.write("\t        //console.log(usePage);\r\n");
      out.write("\t        if(currentPath == usePage){\r\n");
      out.write("\t        \t$(\".navbar-nav > li\").not($(this)).removeClass('active');\r\n");
      out.write("\t        \t$(this).addClass('active');\r\n");
      out.write("\t        } else if(currentPath.indexOf(\"item\") != -1 \r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"part\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"design\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"dDetail\") != -1 \r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"pDetail\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"pup\") != -1\r\n");
      out.write("\t        \t\t|| currentPath.indexOf(\"dup\") != -1){\r\n");
      out.write("                $(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#item\").addClass('active');\r\n");
      out.write("\t        } else if(currentPath.indexOf(\"notice\") != -1 || currentPath.indexOf(\"nlist\") != -1 || currentPath.indexOf(\"ndetail\") != -1){\r\n");
      out.write("                $(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#notice\").addClass('active');\r\n");
      out.write("            } else if (currentPath.indexOf(\"mypage\") != -1 || currentPath.indexOf(\"order\") != -1 || currentPath.indexOf(\"qlist\") != -1  || currentPath.indexOf(\"qa\") != -1 || currentPath.indexOf(\"qdetail\") != -1 || currentPath.indexOf(\"qmlist\") != -1){\r\n");
      out.write("            \t$(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("\t        \t$(\"li#mypage\").addClass('active');\r\n");
      out.write("            } else {\r\n");
      out.write("            \t$(\".navbar-nav > li\").removeClass('active');\r\n");
      out.write("            \t$(\".navbar-nav > li\").eq(0).addClass('active');\r\n");
      out.write("            }\r\n");
      out.write("\t        //console.log(\"참조할 경로 : \"+$(this).children('a').attr('href').substr($(this).children('a').attr('href').lastIndexOf(\"/\")+1));\r\n");
      out.write("\t    });\r\n");
      out.write("\t}); \r\n");
      out.write("</script>\r\n");
      out.write("<!-- 서브메뉴 색상 변경 End -->\r\n");
      out.write("<!-- Modal Start -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".modal-dialog {\r\n");
      out.write("    width: 300px;\r\n");
      out.write("}\r\n");
      out.write(".modal-footer {\r\n");
      out.write("    height: 70px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".modal-footer .btn {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".input-group-addon {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background: #3276B1;\r\n");
      out.write("}\r\n");
      out.write(".prettyline {\r\n");
      out.write("  height: 5px;\r\n");
      out.write("  border-top: 0;\r\n");
      out.write("  background: #c4e17f;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("    $('.modal-footer > button').click(function(){\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("\t\t\turl : \"/made/login\",\r\n");
      out.write("\t\t\tdata : {id : $('#uLogin').val(), pwd : $('#uPassword').val()},\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\tif(result == \"ok\"){\r\n");
      out.write("\t\t\t\t\talert(\"로그인 성공!\");\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/made/index.jsp\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"로그인 실패!! 입력값을 재확인 하세요!\");\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/made/index.jsp\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, error : function(request,status,error) {\r\n");
      out.write("\t\t\t\talert(\"ERROR code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t\tlocation.href = \"/made/404-page.jsp?message='로그인 서비스 실패'\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("    \t$('#login-modal').modal('hide');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write(" <div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t<p class=\"modal-title\" id=\"myModalLabel\" align=\"center\">\r\n");
      out.write("\t\t\t\t<img src=\"/made/images/logo.png\" style=\"height:30px; width:auto; margin-top: -6px;\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;<b style=\"font-size: 16pt;\">Log in</b></p>\r\n");
      out.write("\t\t\t</div> <!-- /.modal-header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form role=\"form\" id=\"loginform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"uLogin\" class=\"input-group-addon glyphicon glyphicon-user\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"uLogin\" placeholder=\"Login\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> <!-- /.form-group -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"uPassword\" class=\"input-group-addon glyphicon glyphicon-lock\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"uPassword\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /.input-group -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /.form-group -->\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div> <!-- /.modal-body -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"form-control btn btn-default btn-block\">Ok</button>\r\n");
      out.write("\t\t\t</div> <!-- /.modal-footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div><!-- /.modal-content -->\r\n");
      out.write("\t</div><!-- /.modal-dialog -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("<!-- Modal End -->\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 여부를 확인하고 로그인 모달 창 호출 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#mypage ul li a').on(\"click\", function(){\r\n");
      out.write("\t\t\tif($('a').first().text().trim() == \"Login\"){\r\n");
      out.write("\t\t\t\t$(\"#login-modal\").modal();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction noticeErr(){\r\n");
      out.write("\t\talert(\"가입한 회원만 열람이 가능합니다.\");\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"header\" class=\"clearfix\">\r\n");
      out.write("\t<div id=\"top-bar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-7 hidden-xs top-info\">\r\n");
      out.write("\t\t\t\t\t<!--                        <span><i class=\"fa fa-phone\"></i>Phone: (123) 456-7890</span>\r\n");
      out.write("                        <span><i class=\"fa fa-envelope\"></i>Email: firerain4@naver.com</span>-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-5 top-info\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li>");
      out.print(request.getRequestURL());
      out.write("</li> -->\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: auto;\">");
      out.print(loginout);
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t");

							if (m == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/made/views/user/signup.jsp\">&nbsp;회원가입&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- LOGO bar -->\r\n");
      out.write("\t<div id=\"logo-bar\" class=\"clearfix\">\r\n");
      out.write("\t\t<!-- Container -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Logo / Mobile Menu -->\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" style=\"width: 170px;\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/made/index.jsp\"><img src=\"/made/images/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Made\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Container / End -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--LOGO bar / End-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation\r\n");
      out.write("================================================== -->\r\n");
      out.write("\t<div class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 if(m == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"notice\"><a href=\"#\" onclick=\"noticeErr();\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"notice\"><a href=\"/made/nlist?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"item\"><a href=\"#\">DIY 상품</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/designitemlist?page=1\">Designed</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/partitemlist?page=1\">Parts</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"mypage\"><a href=\"#\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/llist\">찜목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(m != null && m.getClassCode().equals("C")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/corderlist\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else if(m != null && m.getClassCode().equals("A")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/aorderlist\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else if(m != null && m.getClassCode().equals("D")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/dorderlist\">주문내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/views/mypage/myinfo.jsp\">회원정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/acheck?page=1\">쪽지함</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(m != null && m.getClassCode().charAt(0) == 'A'){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/qlist?page=1\">1:1문의확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/qmlist?page=1\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(m != null &&(m.getClassCode().equals("A") || m.getClassCode().equals("D"))) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/made/pview?mid=");
      out.print(m.getId());
      out.write("\">수익 분석 차트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/views/faq/faq.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/made/contact.jsp\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.row -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/.container -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\t<!--End Header-->\r\n");
      out.write("\r\n");
      out.write("\t<!--start wrapper-->\r\n");
      out.write("\t<section class=\"wrapper\">\r\n");
      out.write("       <section class=\"page_head\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<h2>주문/배송 조회</h2>\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>You are here:</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/made/index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>마이페이지</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>주문/배송조회</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("        \r\n");
      out.write("        <!--- 여기에 내용을 작성해주세요~ --->\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("        \t\t<div class=\"panel panel-default\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table class=table>\r\n");
      out.write("\t\t\t\t  \t\t<thead>\r\n");
      out.write("\t\t\t\t  \t\t\t<tr><th>주문일자/주문번호</th><th>상품정보</th><th>금액/수량</th><th>주문상태</th><th>관리</th></tr>\r\n");
      out.write("\t\t\t\t  \t\t</thead>\r\n");
      out.write("\t\t\t\t  \t\t<tbody>\r\n");
      out.write("\t\t\t\t  \t\t");
 for(ConsumerOrder e : list) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t<tr><td scope=row>");
      out.print( e.getOrderDate() );
      out.write("<br>(");
      out.print( e.getOrderCode() );
      out.write(")<br>\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\t");
 if(e.getDesignCode() != null ) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t<button type=\"button\" onclick=\"openWin('");
      out.print( e.getOrderCode() );
      out.write("', '");
      out.print( e.getDesignCode() );
      out.write("');\">영수증출력</button></td>\r\n");
      out.write("\t\t\t\t\t  \t\t<td><div class=\"c_product\"><img alt=\"상품이미지\" src=\"/made/images/items/designed/");
      out.print( e.getDesignImg() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t  \t\t<div class=\"c_product_description\"><a href=\"/made/dDetail?id=");
      out.print( e.getDesignCode() );
      out.write('"');
      out.write('>');
      out.print( e.getDesignTitle() );
      out.write("</a></div></div></td><td>");
      out.print( e.getDesignprice() * e.getOrderCount() );
      out.write("<br>(");
      out.print( e.getOrderCount() );
      out.write("개)</td>\r\n");
      out.write("\t\t\t\t\t  \t\t");
 if(e.getShipCompanyName() == null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t<td><span>결제 완료</span><br><br>\r\n");
      out.write("\t\t\t\t\t  \t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t<td><span>배송 중</span><br><br>\r\n");
      out.write("\t\t\t\t\t  \t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t");
 if(e.getShipCompanyName() != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( e.getShipCompanyName() );
      out.write("<br>");
      out.print( e.getOrderShipCode() );
      out.write("<br><button onclick=\"check_ship('");
      out.print( e.getShipCompanyName() );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( e.getOrderShipCode() );
      out.write(")\">배송추적</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td><td><button>반품요청</button><br><button>교환요청</button></td></tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" onclick=\"openWin('");
      out.print( e.getOrderCode() );
      out.write("', '");
      out.print( e.getPartCode() );
      out.write("');\">영수증출력</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><div class=\"c_product\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(e.getPartCategory().equals("WOOD")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"상품이미지\" src=\"/made/images/items/parts/wood/");
      out.print( e.getPartImg() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else if(e.getPartCategory().equals("STEEL")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"상품이미지\" src=\"/made/images/items/parts/steel/");
      out.print( e.getPartImg() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else if(e.getPartCategory().equals("PLASTIC")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"상품이미지\" src=\"/made/images/items/parts/plastic/");
      out.print( e.getPartImg() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"상품이미지\" src=\"/made/images/items/parts/etc/");
      out.print( e.getPartImg() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"c_product_description\"><a href=\"/made/pDetail?id=");
      out.print( e.getPartCode() );
      out.write('"');
      out.write('>');
      out.print( e.getPartTitle() );
      out.write("</a></div></div></td><td>");
      out.print( e.getPartPrice() * e.getOrderCount() );
      out.write("<br>(");
      out.print( e.getOrderCount() );
      out.write("개)</td>\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(e.getShipCompanyName() == null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t<td><span>결제 완료</span><br><br>\r\n");
      out.write("\t\t\t\t\t  \t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t\t<td><span>배송 중</span><br><br>\r\n");
      out.write("\t\t\t\t\t  \t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(e.getShipCompanyName() != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( e.getShipCompanyName() );
      out.write("<br>");
      out.print( e.getOrderShipCode() );
      out.write("<br><button onclick=\"check_ship('");
      out.print( e.getShipCompanyName() );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( e.getOrderShipCode() );
      out.write(")\">배송추적</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td><td><button>반품요청</button><br><button>교환요청</button></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<nav aria-label=\"Page navigation\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t  <ul class=\"pagination pagination-sm\">\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t   \t  ");
 if(currentPage <= 1) { 
      out.write("\r\n");
      out.write("\t\t\t\t        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t      ");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t     \t<a href=\"/made/corderlist?page=");
      out.print( currentPage - 1 );
      out.write("\" aria-label=\"Previous\">\r\n");
      out.write("\t\t\t\t        \t<span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t      \t</a>\r\n");
      out.write("\t\t\t\t      ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    ");
 for(int p = startPage; p<= endPage; p++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">");
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/made/corderlist?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t");
 if(currentPage == maxPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/made/corderlist?page=");
      out.print( currentPage + 1 );
      out.write("\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t        \t<span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t      \t</a>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("        \t</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\t<!--start footer-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\"> -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Who's MAːDÆ</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<p>본 프로젝트는 KH정보교육원 [NCS]웹 개발 응용SW엔지니어 양성과정_2주차 오후반 3조에서 만든\r\n");
      out.write("\t\t\t\t\t\t\tSemi 프로젝트입니다.<br><br><span class=\"thanksAllOfYou\" style=\"display: none;\">만들다보니 아쉬운 점도 많고, 배운 점도 많지만 확실한 건 잠이 줄었다는 겁니다.<br>\r\n");
      out.write("\t\t\t\t\t\t\t앞으로 다가올 휴일엔 진짜 제대로 잘 수 있을 것 같은 느낌....각설하고... 팀원 분들 모두 고생 많으셨습니다.</span></p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact-details-alt\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Address</strong>: 서울시 강남구 역삼동\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Phone</strong>: 010-5688-2293\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>Email</strong>: <a href=\"#\">firerain4@naver.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>About Us</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<p>총 5 명의 구성원으로 이루어져 있습니다. <br>능력자분 연락주세요, 언제든지 환영합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact-details-alt thanksAllOfYou\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><div class=\"testimonial-review\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img style=\"width:45px; height:45px;\"src=\"/made/images/userimage/yoo_boss.jpg\" alt=\"testimoni\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t인간로봇, 유 사장<small>&nbsp;&nbsp; Team. 형설지공 AI사장</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><div class=\"testimonial-review\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img style=\"width:45px; height:45px;\"src=\"/made/images/userimage/nasang.jpg\" alt=\"testimoni\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t정시칼퇴, 나 과장<small>&nbsp;&nbsp; Team. 형설지공 인사과장</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><div class=\"testimonial-review\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img style=\"width:45px; height:45px;\"src=\"/made/images/userimage/hyunsang.gif\" alt=\"testimoni\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t본부장은 임 본부장<small>&nbsp;&nbsp; Team. 형설지공 기술고문</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><div class=\"testimonial-review\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img style=\"width:45px; height:45px;\"src=\"/made/images/userimage/emilla.jpg\" alt=\"testimoni\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t한조대기중, 김 대리<small>&nbsp;&nbsp; Team. 형설지공 인사요원</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><div class=\"testimonial-review\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img style=\"width:45px; height:45px;\"src=\"/made/images/userimage/jjm.jpg\" alt=\"testimoni\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t말년병장, 정대리<small>&nbsp;&nbsp; Team. 형설지공 수석몸짱</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Flickr Gallery</span>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"flickr\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"flickrFeed\" class=\"flickr-feed\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer_bottom\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t&copy; Copyright 2017 MAːDÆ | Powered by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://www.jqueryrain.com/\">jQuery Rain</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer_social\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footbot_social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"fb\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Facbook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twtr\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dribbble\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Dribbble\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"skype\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"Skype\"><i class=\"fa fa-skype\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"rss\" href=\"#.\" data-placement=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tooltip\" title=\"RSS\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<script src=\"/made/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/made/js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<!-- jQuery cookie -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/styleswitch.js?var=1\"></script>\r\n");
      out.write("\t<!-- Style Colors Switcher -->\r\n");
      out.write("\t<!-- ?ver=1 값은 브라우저 확인 시 기존 캐시값이 아닌 변경된 파일을 읽어 오라는 뜻  -->\r\n");
      out.write("\t<script src=\"/made/js/jquery.fractionslider.js\" type=\"text/javascript\"\r\n");
      out.write("\t\tcharset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.smartmenus.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/made/js/jquery.smartmenus.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.jcarousel.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jflickrfeed.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery.isotope.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/swipe.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/made/js/jquery-scrolltofixed-min.js\"></script>\r\n");
      out.write("\t<!-- include summernote css/js-->\r\n");
      out.write("\t<link href=\"/made/api/summernote/dist/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"/made/api/summernote/dist/summernote.js\"></script>\r\n");
      out.write("\t<!-- summer note korean language pack -->\r\n");
      out.write("\t<script src=\"/made/api/summernote/dist/lang/summernote-ko-KR.js\"></script>\r\n");
      out.write("\t<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\t<script src=\"/made/js/project(sk).js\"></script>\r\n");
      out.write("\t<script src=\"/made/js/main.js\"></script>\r\n");
      out.write("\t<!-- Start Style Switcher -->\r\n");
      out.write("\t<div class=\"switcher\"></div>\r\n");
      out.write("\t<!-- End Style Switcher -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Slider Setting -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t$('.slider').fractionSlider({\r\n");
      out.write("\t\t\t\t'fullWidth' : true,\r\n");
      out.write("\t\t\t\t'controls' : true,\r\n");
      out.write("\t\t\t\t'responsive' : true,\r\n");
      out.write("\t\t\t\t'dimensions' : \"1920,450\",\r\n");
      out.write("\t\t\t\t'increase' : true,\r\n");
      out.write("\t\t\t\t'pauseOnHover' : true,\r\n");
      out.write("\t\t\t\t'slideEndAnimation' : true,\r\n");
      out.write("\t\t\t\t'autoChange' : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".thanksAllOfYou\").parent().hover(\r\n");
      out.write("\t\t\t\t\tfunction(){\r\n");
      out.write("\t\t\t\t\t\t$(this).children(\".thanksAllOfYou\").show(\"slow\");\r\n");
      out.write("\t\t\t\t\t},function(){\r\n");
      out.write("\t\t\t\t\t\t$(this).children(\".thanksAllOfYou\").hide(\"slow\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Slider Setting -->");
      out.write("\r\n");
      out.write("\t<!--end footer-->\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">  \r\n");
      out.write("function openWin(order_code, productCode){  \r\n");
      out.write("    window.open(\"/made/receipt?order_code=\"+order_code+\"&productCode=\"+productCode, \"영수증\", \"width=650, height=650, toolbar=no, menubar=no, scrollbars=no, resizable=yes\" );  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var dtd_companys = new Array();\r\n");
      out.write("dtd_companys[\"우체국택배\"] = new Array(\r\n");
      out.write("\t\t13,\r\n");
      out.write("\t\t\"http://service.epost.go.kr/trace.RetrieveRegiPrclDeliv.postal?sid1=\",\r\n");
      out.write("\t\t\"1234567890123 (13자리)\", \"1588-1300\",\r\n");
      out.write("\t\t\"http://parcel.epost.go.kr\");\r\n");
      out.write("dtd_companys[\"대한통운\"] = new Array(\r\n");
      out.write("\t\t10,\r\n");
      out.write("\t\t\"http://www.doortodoor.co.kr/servlets/cmnChnnel?tc=dtd.cmn.command.c03condiCrg01Cmd&invc_no=\",\r\n");
      out.write("\t\t\"1234567890 (10자리)\", \"1588-1255\", \"http://www.doortodoor.co.kr\");\r\n");
      out.write("dtd_companys[\"한진택배\"] = new Array(\r\n");
      out.write("\t\t12,\r\n");
      out.write("\t\t\"http://www.hanjin.co.kr/Delivery_html/inquiry/result_waybill.jsp?wbl_num=\",\r\n");
      out.write("\t\t\"1234567890 (10,12자리)\", \"1588-0011\",\r\n");
      out.write("\t\t\"http://hanex.hanjin.co.kr\");\r\n");
      out.write("dtd_companys[\"로젠택배\"] = new Array(\r\n");
      out.write("\t\t11,\r\n");
      out.write("\t\t\"http://www.ilogen.com/iLOGEN.Web.New/TRACE/TraceView.aspx?gubun=slipno&slipno=\",\r\n");
      out.write("\t\t\"12345678901 (11자리)\", \"1588-9988\", \"http://www.ilogen.com\");\r\n");
      out.write("dtd_companys[\"현대택배\"] = new Array(\r\n");
      out.write("\t\t12,\r\n");
      out.write("\t\t\"http://www.hlc.co.kr/hydex/jsp/tracking/trackingViewCus.jsp?InvNo=\",\r\n");
      out.write("\t\t\"1234567890 (10,12자리)\", \"1588-2121\", \"http://www.hlc.co.kr\");\r\n");
      out.write("dtd_companys[\"KG옐로우캡택배\"] = new Array(\r\n");
      out.write("\t\t11,\r\n");
      out.write("\t\t\"http://www.yellowcap.co.kr/custom/inquiry_result.asp?invoice_no=\",\r\n");
      out.write("\t\t\"12345678901 (11자리)\", \"1588-0123\", \"http://www.yellowcap.co.kr\");\r\n");
      out.write("dtd_companys[\"KGB택배\"] = new Array(10,\r\n");
      out.write("\t\t\"http://www.kgbls.co.kr/sub5/trace.asp?f_slipno=\",\r\n");
      out.write("\t\t\"1234567890 (10자리)\", \"1577-4577\", \"http://www.kgbls.co.kr\");\r\n");
      out.write("dtd_companys[\"EMS\"] = new Array(\r\n");
      out.write("\t\t13,\r\n");
      out.write("\t\t\"http://service.epost.go.kr/trace.RetrieveEmsTrace.postal?ems_gubun=E&POST_CODE=\",\r\n");
      out.write("\t\t\"EE123456789KR (13자리)\", \"1588-1300\",\r\n");
      out.write("\t\t\"http://service.epost.go.kr\");\r\n");
      out.write("dtd_companys[\"DHL\"] = new Array(\r\n");
      out.write("\t\t0,\r\n");
      out.write("\t\t\"http://www.dhl.co.kr/publish/kr/ko/eshipping/track.high.html?pageToInclude=RESULTS&type=fasttrack&AWB=\",\r\n");
      out.write("\t\t\"1234567890 (10자리)\", \"1588-0001\", \"http://www.dhl.co.kr\");\r\n");
      out.write("dtd_companys[\"한덱스\"] = new Array(\r\n");
      out.write("\t\t10,\r\n");
      out.write("\t\t\"http://btob.sedex.co.kr/work/app/tm/tmtr01/tmtr01_s4.jsp?IC_INV_NO=\",\r\n");
      out.write("\t\t\"1234567890 (10자리)\", \"1588-9040\", \"http://www.e-handex.co.kr\");\r\n");
      out.write("dtd_companys[\"FedEx\"] = new Array(\r\n");
      out.write("\t\t12,\r\n");
      out.write("\t\t\"http://www.fedex.com/Tracking?ascend_header=1&clienttype=dotcomreg&cntry_code=kr&language=korean&tracknumbers=\",\r\n");
      out.write("\t\t\"123456789012 (12자리)\", \"080-023-8000\",\r\n");
      out.write("\t\t\"http://www.fedex.com/kr\");\r\n");
      out.write("dtd_companys[\"동부익스프레스\"] = new Array(\r\n");
      out.write("\t\t12,\r\n");
      out.write("\t\t\"http://www.dongbuexpress.co.kr/Html/Delivery/DeliveryCheckView.jsp?item_no=\",\r\n");
      out.write("\t\t\"123456789012 (12자리)\", \"1588-8848\",\r\n");
      out.write("\t\t\"http://www.dongbuexpress.co.kr\");\r\n");
      out.write("dtd_companys[\"CJ GLS\"] = new Array(12,\r\n");
      out.write("\t\t\"http://nexs.cjgls.com/web/service02_01.jsp?slipno=\",\r\n");
      out.write("\t\t\"123456789012 (12자리)\", \"1588-5353\", \"http://www.cjgls.co.kr\");\r\n");
      out.write("dtd_companys[\"UPS\"] = new Array(\r\n");
      out.write("\t\t25,\r\n");
      out.write("\t\t\"http://www.ups.com/WebTracking/track?loc=ko_KR&InquiryNumber1=\",\r\n");
      out.write("\t\t\"M1234567890 (최대 25자리)\", \"1588-6886\",\r\n");
      out.write("\t\t\"http://www.ups.com/content/kr/ko/index.jsx\");\r\n");
      out.write("dtd_companys[\"하나로택배\"] = new Array(\r\n");
      out.write("\t\t10,\r\n");
      out.write("\t\t\"http://www.hanarologis.com/branch/chase/listbody.html?a_gb=center&a_cd=4&a_item=0&fr_slipno=\",\r\n");
      out.write("\t\t\"1234567890 (최대 10자리)\", \"1577-2828\",\r\n");
      out.write("\t\t\"http://www.hanarologis.com\");\r\n");
      out.write("dtd_companys[\"대신택배\"] = new Array(\r\n");
      out.write("\t\t13,\r\n");
      out.write("\t\t\"http://home.daesinlogistics.co.kr/daesin/jsp/d_freight_chase/d_general_process2.jsp?\",\r\n");
      out.write("\t\t\"1234567890123 (13자리)\", \"043-222-4582\",\r\n");
      out.write("\t\t\"http://apps.ds3211.co.kr\");\r\n");
      out.write("dtd_companys[\"경동택배\"] = new Array(11,\r\n");
      out.write("\t\t\"http://www.kdexp.com/sub4_1.asp?stype=1&p_item=\",\r\n");
      out.write("\t\t\"12345678901 (최대11자리)\", \"031-460-2400\", \"http://www.kdexp.com/\");\r\n");
      out.write("dtd_companys[\"이노지스택배\"] = new Array(13,\r\n");
      out.write("\t\t\"http://www.innogis.net/trace02.asp?invoice=\",\r\n");
      out.write("\t\t\"1234567890123 (최대13자리)\", \"1566-4082\",\r\n");
      out.write("\t\t\"http://www.innogis.net/\");\r\n");
      out.write("dtd_companys[\"일양로지스택배\"] = new Array(\r\n");
      out.write("\t\t9,\r\n");
      out.write("\t\t\"http://www.ilyanglogis.com/functionality/tracking_result.asp?hawb_no=\",\r\n");
      out.write("\t\t\"123456789 (9자리)\", \"1588-0002\", \"http://www.ilyanglogis.com/\");\r\n");
      out.write("dtd_companys[\"CVSnet 편의점택배\"] = new Array(10,\r\n");
      out.write("\t\t\"http://was.cvsnet.co.kr/src/ctod_status.jsp?invoice_no=\",\r\n");
      out.write("\t\t\"1234567890 (10자리)\", \"1566-1025\", \"http://www.cvsnet.co.kr/\");\r\n");
      out.write("dtd_companys[\"TNT Express\"] = new Array(\r\n");
      out.write("\t\t13,\r\n");
      out.write("\t\t\"http://www.tnt.com/webtracker/tracking.do?respCountry=kr&respLang=ko&searchType=CON&cons=\",\r\n");
      out.write("\t\t\"GE123456789WW (9,13자리)\", \"1588-0588\",\r\n");
      out.write("\t\t\"http://www.tnt.com/express/ko_kr/site/home.html\");\r\n");
      out.write("dtd_companys[\"HB한방택배\"] = new Array(12,\r\n");
      out.write("\t\t\"http://www.hbtb.co.kr/search/s_search.asp?f_slipno=\",\r\n");
      out.write("\t\t\"123456789012 (12자리)\", \"1588-1059\", \"http://www.hbtb.co.kr/\");\r\n");
      out.write("dtd_companys[\"GTX\"] = new Array(\r\n");
      out.write("\t\t12,\r\n");
      out.write("\t\t\"http://www.gtx2010.co.kr/del_inquiry_result.html?s_gbn=1&awblno=\",\r\n");
      out.write("\t\t\"123456789012 (12자리)\", \"1588-1756\", \"http://www.gtx2010.co.kr\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_ship(company, query){\r\n");
      out.write("\t/* 링크만들기 */\r\n");
      out.write("\tif (company == \"대신택배\") {\r\n");
      out.write("\t\turl = dtd_companys[company][1];\r\n");
      out.write("\t\turl += \"billno1=\" + query.substring(0, 4);\r\n");
      out.write("\t\turl += \"&billno2=\" + query.substring(4, 7);\r\n");
      out.write("\t\turl += \"&billno3=\" + query.substring(7, 13);\r\n");
      out.write("\t} else if (dtd_companys[company][1]) {\r\n");
      out.write("\t\turl = dtd_companys[company][1] + query;\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.open(url, \"_blank\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
